types = ['german', 'japanese', 'vegan', 'french', 'african', 'american', 'barbecue', 'chinese', 'thai',
         'mexican', 'indian', 'cafe', 'pizza', 'italian']

restaurant_data = [['german', "Mr. Dunderbak's Biergarten and Brewery", '4.7', "14929 Bruce B Downs Blvd"],
['german', "Schiller's German Delicatessen", '4.8', "4327 W El Prado Blvd"],
['japanese', "Samurai Blue Sushi & Sake Bar", '4.2', "1600 E 8th Ave"],
['japanese', "Sushi House", '4.4', "1901 N 19th Ave"],
['japanese', "SoHo Sushi", '4.5', "3218 W Kennedy Blvd"],
['vegan', "Ybor City Vegan Deli", '4.5', "1903 N 19th St"],
['vegan', "Pure Kitchen", '4.9', "3214 W Kennedy Blvd"],
['vegan', "Nana's Restaurant and Juice Bar", '5.0', "1601 E 4th Ave"],
['french', "CHEZ FABY", '4.6', "500 N Tampa St"],
['french', "Mise en Place", '4.6', "442 W Kennedy Blvd"],
['french', "Restaurant BT", '4.6', "2507 S Macdill Ave"],
['african', "Queen of Sheba", '4.5', "11001 N 56th St"],
['african', "Steaming Pots West Africa Cuisine", '4.7', "1109 W Waters Ave"],
['african', "Mitmita Ethiopian", '4.7', "4901 W Linebaugh Ave"],
['american', "The Bricks", '4.5', "1327 E 7th Ave"],
['american', "Ulele", '4.5', "1810 N Highland Ave"],
['american', "Hattricks", '4.4', "107 E Franklin St"],
['barbecue', "Big John's Alabama BBQ", '4.3', "5707 N 40th St"],
['barbecue', "Al's Finger Licking Good Bar-B-Que", '4.7', "1609 Angel Oliva Senior St"],
['barbecue', "Wicked Oak BarbeQue", '4.7', "6607 N Florida Ave"],
['chinese', "Ming Garden", '4.4', "1600 E 8th Ave"],
['chinese', "Yummy House China Bistro", '4.3', "2620 E Hillsborough Ave"],
['chinese', "China Wok", '4.5', "4058 Fiesta Plaza"],
['thai', "Kombo Kitchen", '4.9', "5009 S Macdill Ave"],
['thai', "Thai Mama", '4.6', "8130 W Waters Ave"],
['thai', "Benjarong Thai", '4.4', "14402 N Dale Mabry"],
['mexican', "Los Chapos Tacos", '4.4', "951 E 7th Ave"],
['mexican', "Muchachas", '4.4', "1910 N Ola Ave"],
['mexican', "Catrina's Tacos and Tequila Bar", '4.3', "1611 N Howard Ave"],
['mexican', "Miguelitos Taqueria Y Tequilas", '4.3', "2702 W Kennedy Blvd"],
['indian', "Flames Indian Cuisine", '4.4', "2601 S Macdill Ave"],
['indian', "Rasoi Indian Cuisine", '4.4', "1701 E 8th Ave"],
['indian', "Curry Leaves", '4.3', "4843 W Kennedy Blvd"],
['cafe', "La Creperia Cafe", '4.3', "1729 E 7th Ave"],
['cafe', "Caffe Fresco & Marketplace", '4.7', "101 E Kennedy Blvd"],
['cafe', "Cafe Perera", '4.7', "601 N Morgan St"],
['pizza', "Due Amici", '4.7', "1724 E 7th Ave"],
['pizza', "New York New York Pizza", '4.4', "1512 E 7th Ave"],
['pizza', "Tampa Pizza Company", '4.4', "77 N Ashley Dr"],
['italian', "La Terrazza", '4.7', "1729 E 7th Ave"],
['italian', "Casa Santo Stefano", '4.6', "1607 N 22nd St"],
['italian', "Cena", '4.5', "1208 E Kennedy Blvd"]]